version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    hostname: app
    tty: true
    depends_on:
      - db
    networks:
      - fullcycle-node-network

  nginx:
    image: nginx:1.23.0-alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./server:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - fullcycle-node-network

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - database:/var/lib/mysql
    tty: true
    networks:
      - fullcycle-node-network

volumes:
  database:
    name: fullcycle-database

networks:
  fullcycle-node-network:
    driver: bridge
